### ISSUE TITLE
use TokenMagic.addFilters(args[1].sourceToken, params); for AA.

### ISSUE THREAD

**Issue by silentmark** [Txus5012/WFRP4e-FX#3]
Hi, 

i would suggest to change the:

```await TokenMagic.addFiltersOnSelected(params);```

to 

```await TokenMagic.addFilters(args[1].sourceToken, params);```

This would fix few issues when effects are added in async mode after other code (i.e. hooks) when selected tokens are already changed and animation is run on wrong element.

**Comment by Txus5012** [comment]
Thanks.
Can you tell me an example of those issues?

**Comment by silentmark** [comment]
Just try to open a card of token A, and then, select token B on canvas. If you apply effect on opened card, the animation will be shown on selected token instead

**Comment by Txus5012** [comment]
Worked perfectly. I've applied it to all effects, when adding and removing them. Also applied it to the light and vision effects (for Ablaze and Unconscious).
Thanks.
